import { type CVData } from "./types";

export const cvData: CVData = {
  name: "ALEKSEY LOVCHIKOV",
  title: "Senior Full-Stack Developer",
  contacts: {
    email: "aleksey.lovchikov@gmail.com",
    github: "github.com/alekseylovchikov",
    telegram: "@jwebbb",
  },
  about:
    "Passionate Full-Stack Developer with 8+ years of experience building scalable web applications. I take full responsibility for tasks and see them through to completion, even when facing new challenges or complex problems. I'm not afraid of difficulties and always conduct thorough research to ensure quality results. My expertise spans both frontend and backend development, complemented by knowledge in DevOps, databases, and system architecture, allowing me to understand and support the entire development lifecycle.",
  skills: [
    {
      title: "Frontend",
      items: [
        "ReactJS",
        "Redux",
        "VueJS",
        "AngularJS",
        "NextJS",
        "TypeScript",
        "JavaScript",
        "HTML5",
        "CSS3",
        "SCSS",
        "React Native",
      ],
    },
    {
      title: "Backend",
      items: [
        "PHP",
        "Laravel",
        "NestJS",
        "ExpressJS",
        "Node.js",
        "RESTful APIs",
        "GraphQL",
        "Golang",
        "Gin",
        "Fiber",
        "GORM",
        "sqlx",
        "context",
        "goroutines",
      ],
    },
    {
      title: "Databases",
      items: ["MySQL", "PostgreSQL", "MongoDB"],
    },
    {
      title: "Tools & DevOps",
      items: [
        "Git",
        "Docker",
        "Webpack",
        "Vite",
        "Rollup",
        "Parcel",
        "Storybook",
        "Jest",
        "React Testing Library",
        "Vitest",
        "Playwright",
        "Puppeteer",
        "Selenium",
        "Appium",
        "Postman",
        "Insomnia",
        "Swagger",
        "OpenAPI",
        "Cypress",
        "CI/CD",
      ],
    },
  ],
  experience: [
    {
      position: "Senior Frontend Developer ReactJS/TypeScript",
      company: "Apicworld ltd",
      location: "Limassol, Cyprus",
      period: "2024 - Present",
      responsibilities: [
        "Developing and maintaining complex ReactJS applications using TypeScript, ensuring type safety and code quality",
        "Designing and implementing scalable frontend architecture with focus on component reusability, performance optimization, and maintainability",
        "Building responsive, accessible user interfaces with modern CSS frameworks and ensuring cross-browser compatibility",
        "Implementing state management solutions (Redux, Context API) and optimizing application performance through code splitting and lazy loading",
        "Working with RESTful APIs and GraphQL, handling data fetching, caching strategies, and error handling",
        "Writing comprehensive unit and integration tests using Jest, React Testing Library, and Vitest, achieving high code coverage",
        "Leading frontend code reviews, establishing coding standards, and mentoring junior developers",
        "Collaborating with UI/UX designers to translate designs into pixel-perfect, interactive components using Figma",
        "Optimizing application performance through profiling, bundle analysis, and implementing best practices for React rendering",
        "Integrating third-party libraries and services, managing dependencies, and ensuring security best practices",
        "Participating in technical decision-making, architecture discussions, and contributing to frontend development roadmap",
      ],
    },
    {
      position: "Senior Frontend Developer",
      company: "Mayflower",
      location: "Limassol, Cyprus",
      period: "2022 - 2024",
      responsibilities: [
        "Led development of an innovative AI-first text editor application from concept to production",
        "Built comprehensive user dashboard and account management system with modern UX patterns",
        "Collaborated closely with UI/UX designers and backend engineers on architecture design and API contracts",
        "Developed key application components ensuring high performance and user experience",
        "Owned entire frontend development strategy and defined technical roadmap",
        "Implemented comprehensive testing strategies ensuring code quality and reliability",
        "Worked in agile environment with frequent releases, A/B testing, and continuous product improvement",
        "Established modern frontend architecture patterns and development best practices",
      ],
    },
    {
      position: "Middle Frontend Developer",
      company: "Brabens Development",
      location: "Moscow",
      period: "2016 - 2022",
      responsibilities: [
        "Developed administrative panel and user dashboard for traffic exchange platform serving thousands of users",
        "Implemented complex business logic on frontend ensuring data integrity and user experience",
        "Actively participated in grooming sessions, sprint planning, and technical decision-making",
        "Performed task decomposition, estimation, and coordinated with cross-functional teams",
        "Collaborated effectively with Backend developers, QA engineers, and designers in agile environment",
        "Championed introduction of new development tools (Cypress, Storybook) improving team productivity",
        "Created pixel-perfect responsive layouts from Figma designs using SCSS and Styled Components",
        "Wrote comprehensive unit and E2E tests achieving high code coverage",
        "Led code refactoring initiatives to improve maintainability, performance, and scalability",
      ],
    },
  ],
  education: [
    {
      degree: "Bachelor's Degree in Computer Science",
      institution: "Modern University for the Humanities (SGA), Moscow",
      major: "Computer Science and Engineering",
      period: "2008 - 2013",
    },
  ],
  languages: [
    { name: "Russian", level: "Native" },
    { name: "English", level: "B1 (Intermediate)" },
  ],
  additionalInfo: [
    "Open to relocation",
    "Strong problem-solving and analytical skills",
    "Experience with Agile/Scrum methodologies",
    "Passionate about clean code and software architecture",
    "Continuous learner, exploring new technologies",
  ],
};
